version: '3.4'

services:
  auth_service:
    build: ./src
    container_name: auth_service
    depends_on:
      - redis
      - auth_postgres
    ports:
      - "8002"
    env_file:
      - .env
    networks:
      - my_network

  auth_nginx:
    image: nginx:latest
    container_name: auth_nginx
#    volumes:
#      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./src/nginx_config:/etc/nginx/conf.d:ro
    depends_on:
      - auth_service
    ports:
      - "82:82"
    networks:
      - my_network

  auth_postgres:
    image: postgres:15
    container_name: auth_postgres
#    volumes:
#      - ./.data/postgres:/data/postgres
#      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      POSTGRES_DB: ${DB_NAME:-auth_database}
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5434"
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379"
    networks:
      - my_network

networks:
  my_network:
    external: True
