FROM postgres:15

RUN apt-get update \
    && apt-get install -y wget make build-essential postgresql-server-dev-all\
    && rm -rf /var/lib/apt/lists/*

ENV PG_PARTMAN_VERSION v4.7.1

# Install pg_partman
RUN set -ex \
    # Download pg_partman
    && wget -O pg_partman.tar.gz "https://github.com/pgpartman/pg_partman/archive/$PG_PARTMAN_VERSION.tar.gz" \
    # Create a folder to put the src files in 
    && mkdir -p /usr/src/pg_partman \
    # Extract the src files
    && tar \
        --extract \
        --file pg_partman.tar.gz \
        --directory /usr/src/pg_partman \
        --strip-components 1 \
    # Delete src file tar
    && rm pg_partman.tar.gz \
    # Move to src file folder
    && cd /usr/src/pg_partman \
    # Build the extension
    && make \
    # Install the extension
    && make NO_BGW=1 install \
    # Delete the src files for pg_partman
    && rm -rf /usr/src/pg_partman \
    # Delete the dependancies for downloading and building the extensions, we no longer need them
    # && apk del .fetch-deps .build-deps\
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the init script
# The Docker Postgres initd script will run anything 
# in the directory /docker-entrypoint-initdb.d
COPY ./src/initdb.sh /docker-entrypoint-initdb.d/initdb.sh


# FROM postgres:15

# RUN apt-get update \
#     && apt-get install -y wget make build-essential postgresql-server-dev-all \
#     && rm -rf /var/lib/apt/lists/*

# ENV PG_PARTMAN_VERSION v4.7.1

# # Установка pg_partman
# RUN set -ex \
#     && wget -O pg_partman.tar.gz "https://github.com/pgpartman/pg_partman/archive/$PG_PARTMAN_VERSION.tar.gz" \
#     && mkdir -p /usr/src/pg_partman \
#     && tar \
#         --extract \
#         --file pg_partman.tar.gz \
#         --directory /usr/src/pg_partman \
#         --strip-components 1 \
#     # && rm pg_partman.tar.gz \
#     && cd /usr/src/pg_partman \
#     && make \
#     && make install \
#     # && rm -rf /usr/src/pg_partman \
#     # && apt-get autoremove -y \
#     # && apt-get clean \
#     # && rm -rf /var/lib/apt/lists/*

# # # Copy the init script
# # # The Docker Postgres initd script will run anything 
# # # in the directory /docker-entrypoint-initdb.d
# COPY ./src/initdb.sh /docker-entrypoint-initdb.d/initdb.sh